# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0159853d1ab6ca132d2b1b58a96e7e58c55ea8b5f5f84c6a5fa24788564a6ca784cb5121f4ef05f1577ffd5865f88086520edbb257f2a0c889bce429b20c2ac

test:
  secret_key_base: 967810b1132930fac36c7f701f44a61294898b866a5b83e8636d8e3fbfd7c624d88de2968ab16ef5258c1b4651e82d3afbd32dfd037cbec894754c163068f1c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
